/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daniel' at '2/16/18 3:09 PM' with Gradle 3.2.1
 *
 * @author daniel, @date 2/16/18 3:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
